---@class bs_uiHelper
local ui = {}

---Comment = TODO:

-- ui.Alchemy = require("BeefStranger.uiHelper.menu.MenuAlchemy")
-- ui.Attributes = require("BeefStranger.uiHelper.menu.MenuAttributes")
-- ui.AttributesList = require("BeefStranger.uiHelper.menu.MenuAttributesList")
-- ui.Audio = require("BeefStranger.uiHelper.menu.MenuAudio")
ui.Barter = require("BeefStranger.uiHelper.menu.MenuBarter")
-- ui.BirthSign = require("BeefStranger.uiHelper.menu.MenuBirthSign")
-- ui.Book = require("BeefStranger.uiHelper.menu.MenuBook")
-- ui.ChooseClass = require("BeefStranger.uiHelper.menu.MenuChooseClass")
-- ui.ClassChoice = require("BeefStranger.uiHelper.menu.MenuClassChoice")
-- ui.ClassMessage = require("BeefStranger.uiHelper.menu.MenuClassMessage")
-- ui.Console = require("BeefStranger.uiHelper.menu.MenuConsole")
-- ui.Contents = require("BeefStranger.uiHelper.menu.MenuContents")
-- ui.CreateClass = require("BeefStranger.uiHelper.menu.MenuCreateClass")
-- ui.Ctrls = require("BeefStranger.uiHelper.menu.MenuCtrls")
ui.Dialog = require("BeefStranger.uiHelper.menu.MenuDialog")
ui.Enchantment = require("BeefStranger.uiHelper.menu.MenuEnchantment")
ui.Help = require("BeefStranger.uiHelper.menu.HelpMenu")
-- ui.Input = require("BeefStranger.uiHelper.menu.MenuInput")
-- ui.InputSave = require("BeefStranger.uiHelper.menu.MenuInputSave")
ui.Inventory = require("BeefStranger.uiHelper.menu.MenuInventory")
ui.InventorySelect = require("BeefStranger.uiHelper.menu.MenuInventorySelect")
ui.Journal = require("BeefStranger.uiHelper.menu.MenuJournal")
-- ui.LevelUp = require("BeefStranger.uiHelper.menu.MenuLevelUp")
-- ui.Load = require("BeefStranger.uiHelper.menu.MenuLoad")
-- ui.Loading = require("BeefStranger.uiHelper.menu.MenuLoading")
ui.Magic = require("BeefStranger.uiHelper.menu.MenuMagic")
-- ui.MagicSelect = require("BeefStranger.uiHelper.menu.MenuMagicSelect")
-- ui.Map = require("BeefStranger.uiHelper.menu.MenuMap")
-- ui.MapNoteEdit = require("BeefStranger.uiHelper.menu.MenuMapNoteEdit")
-- ui.Message = require("BeefStranger.uiHelper.menu.MenuMessage")
ui.Multi = require("BeefStranger.uiHelper.menu.MenuMulti")
-- ui.Name = require("BeefStranger.uiHelper.menu.MenuName")
-- ui.Notify1 = require("BeefStranger.uiHelper.menu.MenuNotify1")
-- ui.Notify2 = require("BeefStranger.uiHelper.menu.MenuNotify2")
-- ui.Notify3 = require("BeefStranger.uiHelper.menu.MenuNotify3")
-- ui.Options = require("BeefStranger.uiHelper.menu.MenuOptions")
ui.Persuasion = require("BeefStranger.uiHelper.menu.MenuPersuasion")
-- ui.Prefs = require("BeefStranger.uiHelper.menu.MenuPrefs")
-- ui.Quantity = require("BeefStranger.uiHelper.menu.MenuQuantity")
-- ui.Quick = require("BeefStranger.uiHelper.menu.MenuQuick")
-- ui.RaceSex = require("BeefStranger.uiHelper.menu.MenuRaceSex")
ui.Repair = require("BeefStranger.uiHelper.menu.MenuRepair")
ui.RestWait = require("BeefStranger.uiHelper.menu.MenuRestWait")
-- ui.Save = require("BeefStranger.uiHelper.menu.MenuSave")
ui.Scroll = require("BeefStranger.uiHelper.menu.MenuScroll")
ui.Services = require("BeefStranger.uiHelper.menu.MenuServices")
ui.SetValues = require("BeefStranger.uiHelper.menu.MenuSetValues")
-- ui.Skills = require("BeefStranger.uiHelper.menu.MenuSkills")
-- ui.SkillsList = require("BeefStranger.uiHelper.menu.MenuSkillsList")
-- ui.Specialization = require("BeefStranger.uiHelper.menu.MenuSpecialization")
ui.Spellmaking = require("BeefStranger.uiHelper.menu.MenuSpellmaking")
ui.Stat = require("BeefStranger.uiHelper.menu.MenuStat")
-- ui.StatReview = require("BeefStranger.uiHelper.menu.MenuStatReview")
-- ui.SwimFillBar = require("BeefStranger.uiHelper.menu.MenuSwimFillBar")
-- ui.TimePass = require("BeefStranger.uiHelper.menu.MenuTimePass")
-- ui.Topic = require("BeefStranger.uiHelper.menu.MenuTopic")
-- ui.Video = require("BeefStranger.uiHelper.menu.MenuVideo")

ui.ID = require("BeefStranger.uiHelper.menu.ID")

return ui